### ISSUE TITLE
venv generation fails when pg_config is not installed.

### ISSUE THREAD

**Issue by dhegberg** [aws/amazon-mwaa-docker-images#52]
**Describe the bug**

The venv generation requires that either pg_config installed to build from source or psycopg2-binary from pip as an alternative to psycopg2-binary.

Ideally psycopg2-binary should be installed for a dev build, but pg_config used for a production build.

Barring that, the readme should include instructions for installing pg_config.

---

**To Reproduce**

When running set-up as per README:

```
$ python3 create_venvs.py

...
Collecting psycopg2
  Downloading psycopg2-2.9.9.tar.gz (384 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 384.9/384.9 kB 12.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running egg_info
      creating /private/var/folders/7k/l2zfsmjj7gq3w4fyhg6jq1qr0000gn/T/pip-pip-egg-info-9tecja4g/psycopg2.egg-info
      writing /private/var/folders/7k/l2zfsmjj7gq3w4fyhg6jq1qr0000gn/T/pip-pip-egg-info-9tecja4g/psycopg2.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/7k/l2zfsmjj7gq3w4fyhg6jq1qr0000gn/T/pip-pip-egg-info-9tecja4g/psycopg2.egg-info/dependency_links.txt
      writing top-level names to /private/var/folders/7k/l2zfsmjj7gq3w4fyhg6jq1qr0000gn/T/pip-pip-egg-info-9tecja4g/psycopg2.egg-info/top_level.txt
      writing manifest file '/private/var/folders/7k/l2zfsmjj7gq3w4fyhg6jq1qr0000gn/T/pip-pip-egg-info-9tecja4g/psycopg2.egg-info/SOURCES.txt'

      Error: pg_config executable not found.

      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:

          python setup.py build_ext --pg-config /path/to/pg_config build ...

      or with the pg_config option in 'setup.cfg'.

      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.

      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).

      [end of output]


```

---

**System Information**

- OS: Tested on MacOS and Arch linux.
- Kernel version: [e.g. 6.2.0-39-generic]
- System architecture: [e.g. x86_64]: Apple M2 for MacOS and x86_64 for linux.
- Browser version (if the bug report is related to the web server): [e.g. Firefox 121.0 (64-bit)]
- Airflow version used:
- aws-mwaa-docker-images commit ID:

---

**Expected behavior**

---

**Screenshots**

---

**Additional context**

**Comment by dhegberg** [comment]
https://github.com/aws/amazon-mwaa-docker-images/pull/145

**Comment by maslick** [comment]
@dhegberg how did you resolve this? I am still getting the same error (using the latest changes in main branch) for Airflow 2.10.3 (running on AmazonLinux2023):

```bash
python3 create_venvs.py --target production
...

>>> Creating a virtual environment under the path images/airflow/2.10.3/.venv...
> Virtualenv already exists in images/airflow/2.10.3/.venv
> Upgrade pip...
Requirement already satisfied: pip in ./images/airflow/2.10.3/.venv/lib64/python3.11/site-packages (25.2)

> Production build selected. Using default requirements.
> Install dependencies from images/airflow/2.10.3/requirements.txt...
Requirement already satisfied: apache-airflow==2.10.3 in ./images/airflow/2.10.3/.venv/lib64/python3.11/site-packages (from apache-airflow[celery,statsd]==2.10.3->-r images/airflow/2.10.3/requirements.txt (line 9)) (2.10.3)
Collecting psycopg2 (from -r images/airflow/2.10.3/requirements.txt (line 15))
  Using cached psycopg2-2.9.11.tar.gz (379 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      /tmp/pip-build-env-lvlgtk8s/overlay/lib/python3.11/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!
      
              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:
      
              License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)
      
              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************
      
      !!
        self._finalize_license_expression()
      running egg_info
      writing psycopg2.egg-info/PKG-INFO
      writing dependency_links to psycopg2.egg-info/dependency_links.txt
      writing top-level names to psycopg2.egg-info/top_level.txt
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/mnt/data/workspace/amazon-mwaa-docker-images/create_venvs.py", line 151, in <module>
    main()
  File "/mnt/data/workspace/amazon-mwaa-docker-images/create_venvs.py", line 143, in main
    create_venv(
  File "/mnt/data/workspace/amazon-mwaa-docker-images/create_venvs.py", line 62, in create_venv
    pip_install(venv_path, "-r", str(requirements_path))
  File "/mnt/data/workspace/amazon-mwaa-docker-images/create_venvs.py", line 112, in pip_install
    subprocess.run(
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['images/airflow/2.10.3/.venv/bin/python', '-m', 'pip', 'install', '-r', 'images/airflow/2.10.3/requirements.txt']' returned non-zero exit status 1.
```

**Comment by dhegberg** [comment]
The change here https://github.com/aws/amazon-mwaa-docker-images/pull/145 added a parameter to the venv script to use the development binary.
